### PR TITLE
Regenerate with current zproto

### PR DESCRIPTION
**Pull request by michal42**
No functional change intended.

### CODE REVIEW

**Comment by aquette** [comment]
@michal42 is it normal and desired that so many FTY_PROTO_EXPORT were removed? Not that we plan to use this on windows, but who knows...

**Comment by michal42** [comment]
I also noticed this and do not know the answer myself. Some change in the zproto generator caused this. But as you say, it's only relevant on Windows. I plan to look into the generator to fix the bug with the _fty_proto_t declaration, so I can look into this as well.

**Comment by aquette** [comment]
@michal42 so to be retitled to [DO NOT MERGE]?

**Comment by michal42** [comment]
No, please merge it, it's a minor issue and I will not be able to fix zproto before the end of the sprint.

**Pull request merged**
